export const ORDERS_PENDING_REQUEST = 'ORDERS_PENDING_REQUEST'
export const ORDERS_PENDING_SUCCESS = 'ORDERS_PENDING_SUCCESS'
export const ORDERS_PENDING_FAIL = 'ORDERS_PENDING_FAIL'

export const ORDERS_PENDING_TODAY_REQUEST = 'ORDERS_PENDING_TODAY_REQUEST'
export const ORDERS_PENDING_TODAY_SUCCESS = 'ORDERS_PENDING_TODAY_SUCCESS'
export const ORDERS_PENDING_TODAY_FAIL = 'ORDERS_PENDING_TODAY_FAIL'

export const ORDERS_COMPLETED_REQUEST = 'ORDERS_COMPLETED_REQUEST'
export const ORDERS_COMPLETED_SUCCESS = 'ORDERS_COMPLETED_SUCCESS'
export const ORDERS_COMPLETED_FAIL = 'ORDERS_COMPLETED_FAIL'

export const ORDERS_COMPLETE_REQUEST = 'ORDERS_COMPLETE_REQUEST'
export const ORDERS_COMPLETE_SUCCESS = 'ORDERS_COMPLETE_SUCCESS'
export const ORDERS_COMPLETE_FAIL = 'ORDERS_COMPLETE_FAIL'

export const ORDERS_CANCEL_REQUEST = 'ORDERS_CANCEL_REQUEST'
export const ORDERS_CANCEL_SUCCESS = 'ORDERS_CANCEL_SUCCESS'
export const ORDERS_CANCEL_FAIL = 'ORDERS_CANCEL_FAIL'

 
