export const SELLREQUESTS_TODAY_REQUEST = 'SELLREQUESTS_TODAY_REQUEST'
export const SELLREQUESTS_TODAY_SUCCESS = 'SELLREQUESTS_TODAY_SUCCESS'
export const SELLREQUESTS_TODAY_FAIL = 'SELLREQUESTS_TODAY_FAIL'

export const SELLREQUESTS_ALL_REQUEST = 'SELLREQUESTS_ALL_REQUEST'
export const SELLREQUESTS_ALL_SUCCESS = 'SELLREQUESTS_ALL_SUCCESS'
export const SELLREQUESTS_ALL_FAIL = 'SELLREQUESTS_ALL_FAIL'

export const SELLREQUESTS_DETAILS_REQUEST = 'SELLREQUESTS_DETAILS_REQUEST'
export const SELLREQUESTS_DETAILS_SUCCESS = 'SELLREQUESTS_DETAILS_SUCCESS'
export const SELLREQUESTS_DETAILS_FAIL = 'SELLREQUESTS_DETAILS_FAIL'

export const SELLREQUESTS_ACCEPT_REQUEST = 'SELLREQUESTS_ACCEPT_REQUEST'
export const SELLREQUESTS_ACCEPT_SUCCESS = 'SELLREQUESTS_ACCEPT_SUCCESS'
export const SELLREQUESTS_ACCEPT_FAIL = 'SELLREQUESTS_ACCEPT_FAIL'
export const SELLREQUESTS_ACCEPT_RESET = 'SELLREQUESTS_ACCEPT_RESET'

