export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_ADMIN_DETAILS_CREATOR_REQUEST = 'USER_ADMIN_DETAILS_CREATOR_REQUEST'
export const USER_ADMIN_DETAILS_CREATOR_SUCCESS = 'USER_ADMIN_DETAILS_CREATOR_SUCCESS'
export const USER_ADMIN_DETAILS_CREATOR_FAIL = 'USER_ADMIN_DETAILS_CREATOR_FAIL'

export const USER_STAFF_PROFILE_CREATOR_REQUEST = 'USER_STAFF_PROFILE_CREATOR_REQUEST'
export const USER_STAFF_PROFILE_CREATOR_SUCCESS = 'USER_STAFF_PROFILE_CREATOR_SUCCESS'
export const USER_STAFF_PROFILE_CREATOR_FAIL = 'USER_STAFF_PROFILE_CREATOR_FAIL'

export const USER_STAFF_LIST_REQUEST = 'USER_STAFF_LIST_REQUEST'
export const USER_STAFF_LIST_SUCCESS = 'USER_STAFF_LIST_SUCCESS'
export const USER_STAFF_LIST_FAIL = 'USER_STAFF_LIST_FAIL'

export const USER_STAFF_DEACTIVATE_REQUEST = 'USER_STAFF_DEACTIVATE_REQUEST'
export const USER_STAFF_DEACTIVATE_SUCCESS = 'USER_STAFF_DEACTIVATE_SUCCESS'
export const USER_STAFF_DEACTIVATE_FAIL = 'USER_STAFF_DEACTIVATE_FAIL'

